relatorio:
	@cd .. && docker-compose run --rm latex pdflatex -interaction=nonstopmode relatorio.tex

apresentacao:
	@cd .. && docker-compose run --rm latex pdflatex -interaction=nonstopmode apresentacao.tex

clean:
	rm -f *.aux *.log *.out *.toc *.nav *.snm *.pdf
